services:
  web:
    build: .
    ports:
      - "8085:80"
    volumes:
      - .:/data
    environment:
      - PERSON=Martina  
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webnet

volumes:
  redis_data:

networks:
  webnet:
    driver: bridge
