services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webnet

volumes:
  redis_data:

networks:
  webnet:
    external: true
